[build]
  command = "pip install -r requirements.txt && python3 app.py"
  publish = "/path/to/your/publish/directory"

[context.production]
  command = "pip install -r requirements.txt && python3 app.py"

[context.deploy-preview]
  command = "pip install -r requirements.txt && python3 app.py"

[context.branch-deploy]
  command = "pip install -r requirements.txt && python3 app.py"
